# Generated by Django 5.1.4 on 2025-01-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='OTP',
            field=models.CharField(blank=True, default=201223, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='reg_status',
            field=models.CharField(choices=[('R', 'registered'), ('P', 'pending')], default='P', max_length=2),
        ),
    ]
