# Generated by Django 5.1.4 on 2025-01-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_onetimepassword_otp_alter_user_reg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='OTP',
            field=models.CharField(blank=True, default=224025, max_length=50),
        ),
    ]
