# Generated by Django 5.1.4 on 2025-01-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_onetimepassword_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='OTP',
            field=models.CharField(blank=True, default=904978, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
