# Generated by Django 5.1.4 on 2025-01-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_onetimepassword_otp_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='OTP',
            field=models.CharField(blank=True, default=479152, max_length=50),
        ),
    ]
