# Generated by Django 5.1.4 on 2025-01-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_onetimepassword_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='OTP',
            field=models.CharField(default='OTQ1Njk5', max_length=50),
        ),
    ]
